#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

APPLICATION="${0##*/}"


  exec sh -e "/usr/local/bin/enter-chroot" "$@" exec xinit /usr/bin/i3

